routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//登陆 登出 注册 视图和操作

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::middleware(['check.install.status'])->group(function (){//安装路由
    Route::get('install','InstallController@installPage');
    Route::post('install','InstallController@installAction');
});
Route::get('/',"IndexController@indexPage");//首页视图
Route::get('login', 'IndexController@loginPage')->name('login');//注册视图
Route::get('register', 'IndexController@registerPage')->name('register');//登录视图
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::post('register', 'Auth\RegisterController@register');

Route::get('goods/show','IndexController@goodShowPage')->name('good.show');


Route::prefix('admin')->group(function () {
    Route::middleware(['auth', 'check.admin.authority'])->group(function () {
        Route::name('admin.')->group(function () {
            Route::get('/','AdminController@indexPage')->name('home');
            Route::prefix('user')->group(function () { //用户
                Route::get('show','AdminController@userShowPage');
                Route::get('add','AdminController@userAddPage')->name('user.add');
                Route::post('add','AdminController@userEditPage');
                Route::get('edit','AdminController@userEditPage')->name('user.edit');
                Route::post('edit','AdminController@userEditPage');
            });
            Route::prefix('order')->group(function () { //订单
                Route::get('show','AdminController@orderShowPage')->name('order.show');
                Route::get('edit/{no}','AdminController@orderEditPage')->name('order.edit');
                Route::post('edit','OrderController@orderEditAction');
            });
            Route::prefix('host')->group(function () { //主机
                Route::get('show','AdminController@hostShowPage')->name('host.show');
                Route::post('create/host/re','HostController@reCreateHost')->where(['id' => '^[0-9]*$']);
            });
            Route::prefix('work/order')->group(function () { //工单
                Route::get('show','AdminController@workOrderShowPage')->name('work.order.show');
                Route::get('detailed/{id}','AdminController@workOrderDetailedPage')->name('work.order.detailed')->where(['id' => '^[0-9]*$']);
                Route::post('close','WorkOrderController@workOrderCloseAction')->name('work.order.close');
                Route::post('reply','WorkOrderController@workOrderAdminReplyAction')->name('work.order.reply');
            });
            Route::prefix('new')->group(function () { //新闻
                Route::get('show','AdminController@newShowPage')->name('new.show');
                Route::get('add','AdminController@newAddPage')->name('new.add');
                Route::post('add','NewController@newAddAction');
                Route::get('edit/{id}','AdminController@newEditAction')->name('new.edit');
                Route::post('edit','NewController@newEditAction');
                Route::post('del','NewController@newDelAction')->name('new.del');
            });
            Route::prefix('good')->group(function () { //商品
                Route::get('show','AdminController@goodShowPage')->name('good.show');
                Route::get('add','AdminController@goodAddPage')->name('good.add');
                Route::get('categories/add','AdminController@goodCategoriesAddPage')->name('good.categories.add');
                Route::get('categories/edit/{id}','AdminController@goodCategoriesEditPage')->name('good.categories.edit')->where(['id' => '^[0-9]*$']);
                Route::get('configure/edit/{id}','AdminController@goodConfigureEditPage')->name('good.configure.edit')->where(['id' => '^[0-9]*$']);
                Route::post('categories/add','GoodController@goodCategoriesAddAction');
                Route::post('categories/edit','GoodController@goodCategoriesEditAction');
                Route::post('categories/del','GoodController@goodCategoriesDelAction')->name('good.categories.del');
                Route::post('configure/del','GoodController@goodConfigureDelAction')->name('good.configure.del');
                Route::get('configure/add','AdminController@goodConfigureAddPage')->name('good.configure.add');
                Route::get('edit/{id}','AdminController@goodEditPage')->name('good.edit');
                Route::post('add','GoodController@goodAddAction');
                Route::post('configure/add','GoodController@goodConfigureAddAction');
                Route::get('edit','AdminController@userEditPage');
                Route::post('edit','GoodController@goodEditAction');
                Route::post('configure/edit','GoodController@goodConfigureEditAction');
                Route::post('del','GoodController@goodDelAction')->name('good.del');
            });
            Route::prefix('user')->group(function () { //全局设置
                Route::get('show','AdminController@userShowPage')->name('user.show');
                Route::get('add','AdminController@userEditPage');
                Route::post('add','AdminController@userEditPage');
                Route::get('edit/{id}','AdminController@userEditPage')->name('user.edit');
                Route::post('edit','UserController@userEditAction');
            });
            Route::prefix('setting')->group(function () { //全局设置
                Route::get('/','AdminController@settingIndexPage')->name('setting.index');
                Route::get('{payment}/pay/config','AdminController@paymentPluginConfigPage')->name('setting.pay');
                Route::post('pay/config','AdminController@paymentPluginConfigAction');
                Route::post('/','AdminController@settingEditAction');
                Route::get('edit','AdminController@userEditPage');
                Route::post('edit','AdminController@userEditPage');
            });
            Route::prefix('server')->group(function () { //服务器设置
                Route::get('show','AdminController@serverShowPage')->name('server.show');
                Route::get('add','AdminController@serverAddPage')->name('server.add');
                Route::get('status/{id}','ServerController@serverStatusPage')->name('server.status')->where(['id' => '^[0-9]*$']);
                Route::post('add','ServerController@serverAddAction');
                Route::get('edit/{id}','AdminController@serverEditPage')->name('server.edit')->where(['id' => '^[0-9]*$']);
                Route::post('edit','ServerController@serverEditAction');
                Route::post('del','ServerController@serverDelAction')->name('server.del');
            });
        });

    });
});

Route::any('/{payment}/order/notify','Payment\PayController@notify');//支付回调
Route::get('/temp/cron',"IndexControaller@tempCronAction");//临时监控

Route::prefix('home')->group(function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('/', 'HomeController@indexPage')->name('home');//用户中心视图
        Route::get('user/profile', 'HomeController@userProfilePage')->name('user.profile');//个人信息视图
        Route::post('user/profile', 'HomeController@userProfileAction');//个人信息操作
        Route::get('buy/{id}', 'HomeController@goodsBuyPage')->name('good.buy');//个人信息视图
        Route::get('pay/{no}', 'HomeController@rePayOrderPage')->name('order.pay.no')->where(['no' => '^[0-9]*$']);//订单未支付再次支付
        Route::get('renew/{id}', 'HomeController@renewHostPage')->name('host.renew')->where(['id' => '^[0-9]*$']);//续费主机
        Route::post('renew/host', 'OrderController@renewHostAction')->name('host.renew.action');//续费主机
        Route::post('pay/re', 'OrderController@rePayOrderAction')->name('order.pay.re');//再次支付
        Route::get('host/show', 'HomeController@hostShowPage')->name('host.show');//主机列表
        Route::get('workorder/show', 'HomeController@workOrderShowPage')->name('work.order.show');//工单列表
        Route::get('workorder/add', 'HomeController@workOrderAddPage')->name('work.order.add');//工单添加
        Route::post('workorder/add', 'WorkOrderController@workOrderAddAction')->name('work.order.add');//工单添加
        Route::get('host/detailed/{id}', 'HomeController@hostDetailedPage')->name('host.detailed');//主机详细
        Route::get('new/show', 'HomeController@newShowPage')-> name('new.show');//新闻列表
        Route::get('new/{id}', 'HomeController@newPostPage')-> name('new.post')->where(['id' => '^[0-9]*$']);//新闻列表
        Route::get('order/show', 'HomeController@orderShowPage')->name('order.show');//新闻列表
        Route::post('order/create', 'OrderController@orderCreateAction')->name('order.create');//消息列表
        Route::any('order/status', 'OrderController@orderCheckStatusAction')->name('order.status');//消息列表

        Route::get('work/order/detailed/{id}','HomeController@workOrderDetailedPage')->name('work.order.detailed')->where(['id' => '^[0-9]*$']);
        Route::get('order/detailed/{id}','HomeController@orderDetailedPage')->name('order.detailed')->where(['no' => '^[0-9]*$']);
        Route::post('reply','WorkOrderController@workOrderReplyAction')->name('work.order.reply');
    });
});

app/Http/Controllers/Server/EasyPanelController.php
<?php

namespace App\Http\Controllers\Server;

use App\HostModel;
use App\Http\Controllers\Controller;
use App\OrderModel;
use App\ServerModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class EasyPanelController extends Controller
{
    /**
     * CURL GET请求
     * @param $url string 请求URL
     * @return mixed 返回获取信息
     */
    protected function curlGet($url)
    {
        $ch = curl_init();  //初始化一个cURL会话
        curl_setopt($ch, CURLOPT_URL, $url);//设置需要获取的 URL 地址
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);//不返回数据
        if (empty($result = curl_exec($ch))) {
            return false;
        };//执行一个cURL会话
        return $result;
    }

    /**
     *
     * @return null
     */
    public function makeGetUrl()
    {
        $server = ServerModel::where([
            ['status', '!-', '0'],
            ['plugin', 'easypanel'],
//            ['id',$id]
        ])->get();
        !$server->isEmpty() ?: $server = null;
        return $server;
    }

    /**
     * 生成签名
     * @param $action
     * @param $key
     * @param $rand
     * @return string
     */
    protected function makeSign($action, $key, $rand)
    {
        return md5($action . $key . $rand);
    }

//    protected function
    protected $suffix = '/api/index.php';
    protected $protocol = 'http://';

    /**
     * 获取服务器状态 成功返回 接口值 失败返回false
     * @param $server
     * @return bool|mixed
     */
    public function serverStatus($server)
    {
        !empty($server->port) ? $port = $server->port : $port = "3312" . $this->suffix;
        $serverUrl = $server->ip;
        $rand = mt_rand(1000, 9999);
        $url = $this->protocol . $serverUrl . ":" . $port . '?c=whm&a=info&json=1&r=' . $rand . '&s=' . $this->makeSign('info', $server->key, $rand);
        $result = $this->curlGet($url);
        if ($result) {
            $result = json_decode($result, true);
            if ($result['result'] == '200') {
                $back = [];
                empty($result['type'][0][0]) ? $back['type'] = null : $back['type'] = $result['type'][0][0];
                empty($result['os'][0][0]) ? $back['os'] = null : $back['os'] = $result['os'][0][0];
                empty($result['server'][0][0]) ? $back['server'] = null : $back['server'] = $result['server'][0][0];
                empty($result['version'][0][0]) ? $back['version'] = null : $back['version'] = $result['version'][0][0];
                empty($result['disk_free'][0][0]) ? $back['disk_free'] = null : $back['disk_free'] = $result['disk_free'][0][0];
                empty($result['connect'][0][0]) ? $back['connect'] = null : $back['connect'] = $result['connect'][0][0];
                empty($result['total_run'][0][0]) ? $back['total_run'] = null : $back['total_run'] = $result['total_run'][0][0];
                return $back;
            }
            return false;
        };
        return false;
    }

    /**
     * 创建主机
     * @param $server
     * @param $configure
     * @param $order
     * @return bool
     */
    public function createHost($server, $configure, $order)
    {
        !empty($server->port) ? $port = $server->port : $port = "3312" . $this->suffix;
        $serverUrl = $server->ip;
        $rand = mt_rand(1000, 9999);
        $sign = $this->makeSign('add_vh', $server->key, $rand);
        $name = date('y') . $rand . substr(time(), 4);
        $password = substr(md5($rand . $configure->title . time() . $serverUrl), 16);
        $configureUrl = '&json=1';
        // 判断设置是否存在 ? 默认值（可空）: 连接
        //构建URL请求接口URL
        !$configure->web_quota ?: $configureUrl .= "&web_quota=" . $configure->web_quota;
        !$configure->db_quota ?: $configureUrl .= "&db_quota=" . $configure->db_quota;
        !$configure->ftp ? $configureUrl .= "&ftp=-1" : $configureUrl .= "&ftp=" . (int)$configure->ftp;
        !$configure->subdir ? $configureUrl .= "&subdir=wwwroot" : $configureUrl .= "&subdir=" . $configure->subdir;
        !$configure->domain ? $configureUrl .= "&domain=-1" : $configureUrl .= "&domain=" . $configure->domain;
        !$configure->subdir_flag ? $configureUrl .= "&subdir_flag=1" : $configureUrl .= "&subdir_flag=" . (int)$configure->subdir_flag;
        !$configure->max_subdir ? $configureUrl .= "&subdir_flag=0" : $configureUrl .= "&max_subdir=" . $configure->max_subdir;
        !$configure->db_type ?: $configureUrl .= "&db_type=" . $configure->db_type;
        !$configure->templete ? $configureUrl .= "&templete=php" : $configureUrl .= "&templete=" . $configure->templete;
        !$configure->module ? $configureUrl .= "&module=php" : $configureUrl .= "&module=" . $configure->module;
        !$configure->mysql_verison ?: $configureUrl .= "&subtemplete=" . $configure->mysql_verison;
//        !$configure->access ? $configureUrl .= "&access=access.xml": $configureUrl .= "&access=" . $configure->access;
        !$configure->subdir_flag ?: $configureUrl .= "&subtemplete=" . $configure->mysql_verison;
        $url = $this->protocol . $serverUrl . ':' . $port . '?c=whm&a=add_vh&r=' . $rand . '&s=' . $sign . "&name=" . $name . "&passwd=" . $password . "&init=1" . $configureUrl;
        $result = $this->curlGet($url);
        if ($result) {
            $result = json_decode($result, true);
            if ($result['result'] == 200) {
                $tempPort = !empty($server->port) ? $server->port : ":3312/vhost/";
                $host = HostModel::create([
                    'order_id' => $order->id,
                    'user_id' => $order->user_id,
                    'host_name' => $name,
                    'host_pass' => $password,
                    'host_panel' => 'EasyPanel',
                    'host_url' => $this->protocol . $serverUrl . $tempPort
                ]);
                return $host;
            }
            Log::info('EasyPanel Create Host Errror', ['url' => $url]);
            return false;
        }
        return false;
    }

    //TODO 获取主机信息
    public function getVh($server, $host)
    {
        !empty($server->port) ? $port = $server->port : $port = "3312" . $this->suffix;
        $serverUrl = $server->ip;
        $rand = mt_rand(1000, 9999);
        $sign = $this->makeSign('add_vh', $server->key, $rand);
        $url = $this->protocol . $serverUrl . ':' . $port . "";
    }

    /**
     * 续费主机
     * ep面板没法限定时间
     * @return bool
     */
    public function renewHost()
    {
        return true;
    }

    /**
     * 停用主机
     * @param $server
     * @param $host
     * @return false|object
     */
    public function closeHost($server, $host)
    {
        !empty($server->port) ? $port = $server->port : $port = "3312" . $this->suffix;
        $serverUrl = $server->ip;
        $rand = mt_rand(1000, 9999);
        $sign = $this->makeSign('update_vh', $server->key, $rand);
        $url = $this->protocol . $serverUrl . ':' . $port . "?c=whm&a=update_vh&&r=" . $rand . "&s=" . $sign . "&name=" . $host->host_name . "&status=1&json=1";
        $result = $this->curlGet($url);
        if ($result) {
            $result = json_decode($result, true);
            if ($result['result'] == 200) {
                return $host;
            }
            Log::info('EasyPanel close host error', ['url' => $url]);
            return false;
        }
        return false;
    }
}

resources/views/admin/themes/default/servers/add.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">添加服务器</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{route('admin.server.add')}}">
                        {{csrf_field()}}
                        <h6 class="heading-small text-muted mb-4">基础信息</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-username">服务器名称</label>
                                        <input type="text" class="form-control form-control-alternative"
                                               placeholder="服务器名称,便于识别" value="{{old('title')}}" name="title">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务器IP</label>
                                        <input type="text" name="ip" class="form-control form-control-alternative"
                                               value="{{old('ip')}}" placeholder="请填写服务器IP">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务器Key</label>
                                        <input type="text" name="key" class="form-control form-control-alternative"
                                               value="{{old('key')}}" placeholder="服务器安全码（根据服务器插件不同填写，可为空）">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务端口</label>
                                        <input type="text" name="port" class="form-control form-control-alternative"
                                               value="{{old('port')}}" placeholder="API接口端口（默认根据插件使用默认端口，可为空）">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-email">插件</label>
                                        <select class="custom-select" id="inputGroupSelect02" name="plugin">
                                            @if(!empty($serverPlugin))
                                                @foreach($serverPlugin as $plugin)
                                                    <option value="{{$plugin}}">{{$plugin}}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="新建">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/servers/edit.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.header')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col-xl-12 order-xl-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">编辑服务器</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="post" id="add-form" action="{{action('ServerController@serverEditAction')}}">
                        {{csrf_field()}}
                        <input type="hidden" value="{{$server->id}}" name="id">
                        <h6 class="heading-small text-muted mb-4">基础信息</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-username">服务器名称</label>
                                        <input type="text" class="form-control form-control-alternative"
                                               placeholder="服务器名称,便于识别"
                                               value="{{old('title') ? old('title'): $server->title}}" name="title">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务器IP</label>
                                        <input type="text" name="ip" class="form-control form-control-alternative"
                                               value="{{old('ip') ? old('ip'): $server->ip}}" placeholder="请填写服务器IP">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务器Key</label>
                                        <input type="text" name="key" class="form-control form-control-alternative"
                                               value="{{old('key') ? old('key'): $server->key}}"
                                               placeholder="服务器安全码（根据服务器插件不同填写，可为空）">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">服务端口</label>
                                        <input type="text" name="port" class="form-control form-control-alternative"
                                               value="{{old('port') ? old('port'): $server->port}}"
                                               placeholder="API接口端口（默认根据插件使用默认端口，可为空）">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label" for="input-email">插件</label>
                                        <select class="custom-select" id="inputGroupSelect02" name="plugin">
                                            @if(!empty($serverPlugin))
                                                @foreach($serverPlugin as $plugin)
                                                    <option value="{{$plugin}}"
                                                            {{old('plugin') ? (old('plugin') == $plugin ? "selected" : "") : ($plugin == $server->plugin ? "selected" : "")}}
                                                    >{{$plugin}}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @include('admin.themes.default.layouts.errors')
                        <input type="submit" class="btn btn-primary" value="编辑">
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/themes/default/servers/show.blade.php
@extends('admin.themes.default.layouts.app')

@section('content')
    @include('admin.themes.default.layouts.card')
@endsection

@section('container-fluid')
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">服务器管理</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">服务器名称</th>
                            <th scope="col">服务器IP</th>
                            <th scope="col">状态</th>
                            <th scope="col">插件</th>
                            <th scope="col">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($servers))
                            @foreach($servers as $item)
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <a href="{{route('admin.server.status',['id'=>$item->id])}}"
                                                   class="mb-0 text-sm">{{$item->title}}</a>
                                            </div>
                                        </div>
                                    </th>
                                    <td>
                                        {{$item->ip}}
                                    </td>
                                    <td>
                                                                           <span class="badge badge-dot mr-4">
                                        @switch($item->status)
                                                                                   @case(1)
                                                                                   <i class="bg-success"></i> 正常
                                                                                   @break
                                                                               @endswitch
                                                              </span>
                                    </td>
                                    <td>
                                        {{$item->plugin}}
                                    </td>
                                    <td class="text-left">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item"
                                                   href="{{route('admin.server.edit',['id'=>$item->id])}}">编辑</a>
                                                <a class="dropdown-item" onclick="event.preventDefault();
                                                        document.getElementById('del-server-{{$item->id}}').submit();"
                                                   href="">删除</a>
                                                <form id="del-server-{{$item->id}}"
                                                      action="{{ route('admin.server.del') }}" method="POST"
                                                      style="display: none;">
                                                    {{csrf_field()}}
                                                    <input type="hidden" name="id" value="{{$item->id}}">
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <a href="{{route('admin.server.add')}}" class="btn btn-primary">新增服务器</a>
                </div>
            </div>
        </div>
    </div>
@endsection